<?php

return [
    'organizacoes' => [
        'Escola da Rede Municipal',
        'Escola da Rede Estadual',
        'Escola da Rede Federal',
        'Secretaria Municipal de Educação',
        'Setor Privado',
        'Universidade',
        'Movimentos Sociais e Populares',
        'Movimento dos Trabalhadores Rurais Sem Terra (MST)',
        'Sindicato dos Trabalhadores Rurais',
        'Sindicato de pescadores artesanais',
        'Movimentos antirracistas e de defesa da população negra',
        'Movimentos LGBTQIA+',
        'Movimentos de mulheres e feministas',
        'Movimentos de pessoas com deficiência (PCD)',
        'Movimentos de idosos e terceira idade',
        'Coletivos de juventude periféricos',
        'Movimentos de educação de jovens e adultos (EJA)',
        'Coletivos de cultura popular (capoeira, samba, artesanato)',
        'Grupos de teatro comunitário',
        'Bibliotecas comunitárias e pontos de leitura',
        'Redes de educadores populares',
        'Associações de artesãos e artesãs',
        'Feiras de economia solidária',
        'Conselhos comunitários (saúde, educação, meio ambiente)',
        'Outros',
    ],

    'participante_tags' => [
        'Rede de Ensino',
        'Movimento Social',
        'Como Alfabetizar com Paulo Freire',
    ],

    'demograficos' => [
        'identidade_genero' => [
            'opcoes' => [
                'Mulher Cisgênero',
                'Mulher Transsexual',
                'Homem Cisgênero',
                'Homem Transsexual',
                'Travesti',
                'Não binárie',
                'Prefiro não responder',
                'Outro',
            ],
            'campo_outro' => 'identidade_genero_outro',
            'valor_outro' => 'Outro',
        ],
        'raca_cor' => [
            'opcoes' => [
                'Preta',
                'Parda',
                'Branca',
                'Amarela',
                'Indígena',
                'Prefere não declarar',
            ],
            'campo_outro' => null,
        ],
        'comunidade_tradicional' => [
            'opcoes' => [
                'Não',
                'Povos indígenas',
                'Comunidades Quilombolas',
                'Povos Ciganos',
                'Ribeirinhos',
                'Extrativistas',
                'Outro',
            ],
            'campo_outro' => 'comunidade_tradicional_outro',
            'valor_outro' => 'Outro',
        ],
        'faixa_etaria' => [
            'opcoes' => [
                'Primeira infância (0 a 6 anos)',
                'Criança (7 a 11 anos)',
                'Adolescente (12 a 17 anos)',
                'Adulto (18 a 59 anos)',
                'Idoso (a partir dos 60 anos)',
            ],
            'campo_outro' => null,
        ],
        'pcd' => [
            'opcoes' => [
                'Não',
                'Física',
                'Auditiva',
                'Visual',
                'Intelectual',
                'Múltipla',
            ],
            'campo_outro' => null,
        ],
        'orientacao_sexual' => [
            'opcoes' => [
                'Lésbica',
                'Gay',
                'Bissexual',
                'Heterossexual',
                'Prefere não declarar',
                'Outra',
            ],
            'campo_outro' => 'orientacao_sexual_outra',
            'valor_outro' => 'Outra',
        ],
    ],
];
